name: rmb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  lottie: ^2.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: "^0.12.0"

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter_gen:
  output: lib/resources/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  fonts:
    enabled: true
    outputs:
      class_name: Poppins

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/main_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/image/main_logo.png"
    background_color: "#0E171E"
    theme_color: "#0E171E"
  windows:
    generate: true
    image_path: "assets/image/main_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/image/main_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/image/delete.png
    - assets/image/edit.png
    - assets/image/email.png
    - assets/image/fb.png
    - assets/image/female1.png
    - assets/image/instagram.png
    - assets/image/linkedin.png
    - assets/image/logo.png
    - assets/image/male1.png
    - assets/image/male2.png
    - assets/image/phone.png
    - assets/image/rbm_logo.png
    - assets/image/share.png
    - assets/image/web.png
    - assets/image/whatsapp.png
    - assets/image/unselected_radio.png
    - assets/image/selected_radio.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Poppins-Thin.ttf
          weight: 100
